[tool.poetry]
name = "article"
version = "0.1.0"
description = ""
authors = ["Andrii Hrimov <andrii.hrimov@nixsolutions.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
